apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mjd8j74z7-python
  janus-idp.io/tekton: mjd8j74z7-python
  backstage.io/kubernetes-id: mjd8j74z7-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mjd8j74z7-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
